throw legacy error in compile, fix luarocks path in prepare

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -23,6 +23,8 @@ LUA=lua
 cd $BUILD_DIR
 
 mkdir -p bin
+mkdir -p packages
+
 echo "-----> Copying lua to bin"
 cp "$OPT_DIR/lua" "bin/"
 
@@ -31,12 +33,24 @@ echo "-----> Installing packages"
 SITE_CONFIG="$OPT_DIR/luarocks/luarocks/site_config.lua"
 
 if [ "$ENV" != "local" ]; then
-	export PATH=$OPT_DIR:$PATH
-	echo "LUA_INCDIR=[[$OPT_DIR/../include]]" >> $SITE_CONFIG
-	echo "LUA_LIBDIR=[[$OPT_DIR/../lib]]" >> $SITE_CONFIG
+  export PATH=$OPT_DIR:$PATH
+  echo "LUA_INCDIR=[[$OPT_DIR/../include]]" >> $SITE_CONFIG
+  echo "LUA_LIBDIR=[[$OPT_DIR/../lib]]" >> $SITE_CONFIG
 fi
 
-ROCKSPEC=$(ls *.rockspec | head -n 1)
+# use sed because grep halts script with -e when there is no match
+ROCKSPEC=$(ls | sed -n 's/\.rockspec$/&/p' | head -n 1)
+
+if [[ -z "$ROCKSPEC" ]]; then
+  echo "-----> Fatal Error"
+  echo ""
+  echo "       package.lua is no longer supported."
+  echo ""
+  echo "       You must provide a rockspec with your app."
+  echo "       See https://github.com/leafo/heroku-buildpack-lua/blob/master/README.md"
+  echo ""
+  exit 1
+fi
 
 $LUA "$OPT_DIR/prepare.lua" $ROCKSPEC $OPT_DIR 2>&1 | indent
 
